from django.db import models

class oreStarData(models.Model):
    tran_id = models.CharField(max_length=200, null=True)
    original_id = models.CharField(max_length=200, null=True)
    tran_date = models.CharField(max_length=200, null=True)
    tran_status = models.CharField(max_length=200, null=True)
    filer = models.CharField(max_length=200, null=True)
    payee = models.CharField(max_length=200, null=True)
    subtype = models.CharField(max_length=200, null=True)
    amount = models.CharField(max_length=200, null=True)
    agg_amount = models.CharField(max_length=200, null=True)
    payee_id = models.CharField(max_length=200, null=True)
    filer_id = models.CharField(max_length=200, null=True)
    attest_by_name = models.CharField(max_length=200, null=True)
    attest_date= models.CharField(max_length=200, null=True)
    review_by_name = models.CharField(max_length=200, null=True)
    review_date = models.CharField(max_length=200, null=True)
    due_date = models.CharField(max_length=200, null=True)
    occptn_ltr_date = models.CharField(max_length=200, null=True)
    payment_text = models.CharField(max_length=200, null=True)
    purps_desc = models.CharField(max_length=200, null=True)
    intrst_rate = models.CharField(max_length=200, null=True)
    check_numb = models.CharField(max_length=200, null=True)
    trans_status_ind = models.CharField(max_length=200, null=True)
    file_by_name = models.CharField(max_length=200, null=True)
    file_date = models.CharField(max_length=200, null=True)
    addr_book_agent = models.CharField(max_length=200, null=True)
    book_type = models.CharField(max_length=200, null=True)
    title_txt = models.CharField(max_length=200)
    occptn_txt = models.CharField(max_length=200, null=True)
    emp_name = models.CharField(max_length=200, null=True)
    emp_city = models.CharField(max_length=200,null=True)
    emp_state = models.CharField(max_length=200, null=True)
    emploeed_ind = models.CharField(max_length=200, null=True)
    self_employee_ind = models.CharField(max_length=200, null=True)
    addr_line_1 = models.CharField(max_length=200, null=True)
    addr_line_2 = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    zipplus = models.CharField(max_length=200, null=True)
    county = models.CharField(max_length=200, null=True)
    purpose_code = models.CharField(max_length=200, null=True)

    class Meta:
        db_table = 'OreStar Data Scrape'
        managed = True
        verbose_name = 'ModelName'
        verbose_name_plural = 'ModelNames'